### ISSUE TITLE
TypeError: Module specifier, 'application' does not start with "/", "./", or "../"

### ISSUE THREAD

**Issue by gabrieelgomez** [rails/importmap-rails#182] opened 2023-03-31 01:47 UTC
Hello! I got this error while starting my recent rails new app on 7.0.4.2 and ruby 3.2.1

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/23393343/229001912-eb3649ec-b0ea-4266-b9e0-b1850c734ff4.png">

I just did a hello world in the root path and when I see the logs I get this

Gemfile

gem "importmap-rails"

`config/importmap.rb`

```
pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
```

**Comment by morgoth** [comment] 2023-03-31 06:32
This can be ignored as the next line says in the console output https://github.com/rails/importmap-rails/blob/33e26bcffa073196a06b1342009d4a51b8abe08c/app/assets/javascripts/es-module-shims.js#L31-L33

What browser do you use and which version? Vide https://caniuse.com/?search=importmap

**Comment by SylarRuby** [comment] 2023-04-11 18:06
How to resolve this please? The error breaks all other JavaScript from executing.

**Comment by morgoth** [comment] 2023-04-14 09:41
@gabrieelgomez Since this is expected behavior can you close the issue?

**Comment by SylarRuby** [comment] 2023-04-14 09:42
Yup. Can confirm nothing breaks.

**Closed** 2023-04-23 12:54 UTC
